// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: menu.proto

package com.grpc.menu;

public final class MenuOuterClass {
  private MenuOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_proto_menu_grpc_Menu_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_proto_menu_grpc_Menu_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_proto_menu_grpc_MenuRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_proto_menu_grpc_MenuRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_proto_menu_grpc_MenuResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_proto_menu_grpc_MenuResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmenu.proto\022\023com.proto.menu.grpc\"O\n\004Men" +
      "u\022\017\n\007menu_id\030\004 \001(\005\022\021\n\tmenu_name\030\001 \001(\t\022\020\n" +
      "\010menu_url\030\002 \001(\t\022\021\n\tparent_id\030\003 \001(\005\"\232\001\n\013M" +
      "enuRequest\022\n\n\002id\030\n \001(\005\022\017\n\007menu_id\030\004 \001(\005\022" +
      "\021\n\tmenu_name\030\001 \001(\t\022\020\n\010menu_url\030\002 \001(\t\022\021\n\t" +
      "parent_id\030\003 \001(\005\022\r\n\005token\030\006 \001(\t\022\'\n\004menu\030\005" +
      " \003(\0132\031.com.proto.menu.grpc.Menu\"\237\001\n\014Menu" +
      "Response\022\n\n\002id\030\n \001(\005\022\017\n\007menu_id\030\004 \001(\005\022\021\n" +
      "\tmenu_name\030\001 \001(\t\022\020\n\010menu_url\030\002 \001(\t\022\021\n\tpa" +
      "rent_id\030\003 \001(\005\022\'\n\004menu\030\005 \003(\0132\031.com.proto." +
      "menu.grpc.Menu\022\021\n\tstatus_id\030\006 \001(\0052\365\003\n\013Me" +
      "nuService\022O\n\010listMenu\022 .com.proto.menu.g" +
      "rpc.MenuRequest\032!.com.proto.menu.grpc.Me" +
      "nuResponse\022N\n\007addMenu\022 .com.proto.menu.g" +
      "rpc.MenuRequest\032!.com.proto.menu.grpc.Me" +
      "nuResponse\022Q\n\nremoveMenu\022 .com.proto.men" +
      "u.grpc.MenuRequest\032!.com.proto.menu.grpc" +
      ".MenuResponse\022Q\n\nmodifyMenu\022 .com.proto." +
      "menu.grpc.MenuRequest\032!.com.proto.menu.g" +
      "rpc.MenuResponse\022O\n\010getRoute\022 .com.proto" +
      ".menu.grpc.MenuRequest\032!.com.proto.menu." +
      "grpc.MenuResponse\022N\n\007getMenu\022 .com.proto" +
      ".menu.grpc.MenuRequest\032!.com.proto.menu." +
      "grpc.MenuResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_proto_menu_grpc_Menu_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_proto_menu_grpc_Menu_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_proto_menu_grpc_Menu_descriptor,
        new java.lang.String[] { "MenuId", "MenuName", "MenuUrl", "ParentId", });
    internal_static_com_proto_menu_grpc_MenuRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_proto_menu_grpc_MenuRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_proto_menu_grpc_MenuRequest_descriptor,
        new java.lang.String[] { "Id", "MenuId", "MenuName", "MenuUrl", "ParentId", "Token", "Menu", });
    internal_static_com_proto_menu_grpc_MenuResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_proto_menu_grpc_MenuResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_proto_menu_grpc_MenuResponse_descriptor,
        new java.lang.String[] { "Id", "MenuId", "MenuName", "MenuUrl", "ParentId", "Menu", "StatusId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
