// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_area.proto

package com.grpc.user_area;

public interface UserAreaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.user_area.UserArea)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>int32 userId = 2;</code>
   */
  int getUserId();

  /**
   * <code>int32 areaType = 3;</code>
   */
  int getAreaType();

  /**
   * <code>string provinceCode = 4;</code>
   */
  java.lang.String getProvinceCode();
  /**
   * <code>string provinceCode = 4;</code>
   */
  com.google.protobuf.ByteString
      getProvinceCodeBytes();

  /**
   * <code>string cityCode = 5;</code>
   */
  java.lang.String getCityCode();
  /**
   * <code>string cityCode = 5;</code>
   */
  com.google.protobuf.ByteString
      getCityCodeBytes();

  /**
   * <code>string countyCode = 6;</code>
   */
  java.lang.String getCountyCode();
  /**
   * <code>string countyCode = 6;</code>
   */
  com.google.protobuf.ByteString
      getCountyCodeBytes();

  /**
   * <code>string county = 7;</code>
   */
  java.lang.String getCounty();
  /**
   * <code>string county = 7;</code>
   */
  com.google.protobuf.ByteString
      getCountyBytes();

  /**
   * <code>string townCode = 8;</code>
   */
  java.lang.String getTownCode();
  /**
   * <code>string townCode = 8;</code>
   */
  com.google.protobuf.ByteString
      getTownCodeBytes();

  /**
   * <code>string town = 9;</code>
   */
  java.lang.String getTown();
  /**
   * <code>string town = 9;</code>
   */
  com.google.protobuf.ByteString
      getTownBytes();

  /**
   * <code>string villageCode = 10;</code>
   */
  java.lang.String getVillageCode();
  /**
   * <code>string villageCode = 10;</code>
   */
  com.google.protobuf.ByteString
      getVillageCodeBytes();

  /**
   * <code>string village = 11;</code>
   */
  java.lang.String getVillage();
  /**
   * <code>string village = 11;</code>
   */
  com.google.protobuf.ByteString
      getVillageBytes();

  /**
   * <code>string zipCode = 12;</code>
   */
  java.lang.String getZipCode();
  /**
   * <code>string zipCode = 12;</code>
   */
  com.google.protobuf.ByteString
      getZipCodeBytes();

  /**
   * <code>string telephoneCode = 13;</code>
   */
  java.lang.String getTelephoneCode();
  /**
   * <code>string telephoneCode = 13;</code>
   */
  com.google.protobuf.ByteString
      getTelephoneCodeBytes();

  /**
   * <code>string detailName = 14;</code>
   */
  java.lang.String getDetailName();
  /**
   * <code>string detailName = 14;</code>
   */
  com.google.protobuf.ByteString
      getDetailNameBytes();

  /**
   * <code>string shortName = 15;</code>
   */
  java.lang.String getShortName();
  /**
   * <code>string shortName = 15;</code>
   */
  com.google.protobuf.ByteString
      getShortNameBytes();

  /**
   * <code>string merger_name = 16;</code>
   */
  java.lang.String getMergerName();
  /**
   * <code>string merger_name = 16;</code>
   */
  com.google.protobuf.ByteString
      getMergerNameBytes();

  /**
   * <code>string pinyin = 17;</code>
   */
  java.lang.String getPinyin();
  /**
   * <code>string pinyin = 17;</code>
   */
  com.google.protobuf.ByteString
      getPinyinBytes();

  /**
   * <code>float lng = 18;</code>
   */
  float getLng();

  /**
   * <code>float lat = 19;</code>
   */
  float getLat();

  /**
   * <code>string isDefault = 20;</code>
   */
  java.lang.String getIsDefault();
  /**
   * <code>string isDefault = 20;</code>
   */
  com.google.protobuf.ByteString
      getIsDefaultBytes();

  /**
   * <code>int32 create_time = 21;</code>
   */
  int getCreateTime();

  /**
   * <code>int32 create_user = 22;</code>
   */
  int getCreateUser();

  /**
   * <code>int32 update_time = 23;</code>
   */
  int getUpdateTime();

  /**
   * <code>int32 update_user = 24;</code>
   */
  int getUpdateUser();
}
