// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: area.proto

package com.grpc.area;

public interface AreaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.area.AreaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>int32 level_code = 2;</code>
   */
  int getLevelCode();

  /**
   * <code>string parent_code = 3;</code>
   */
  java.lang.String getParentCode();
  /**
   * <code>string parent_code = 3;</code>
   */
  com.google.protobuf.ByteString
      getParentCodeBytes();

  /**
   * <code>string area_code = 4;</code>
   */
  java.lang.String getAreaCode();
  /**
   * <code>string area_code = 4;</code>
   */
  com.google.protobuf.ByteString
      getAreaCodeBytes();

  /**
   * <code>repeated .com.grpc.area.Area area = 5;</code>
   */
  java.util.List<com.grpc.area.Area> 
      getAreaList();
  /**
   * <code>repeated .com.grpc.area.Area area = 5;</code>
   */
  com.grpc.area.Area getArea(int index);
  /**
   * <code>repeated .com.grpc.area.Area area = 5;</code>
   */
  int getAreaCount();
  /**
   * <code>repeated .com.grpc.area.Area area = 5;</code>
   */
  java.util.List<? extends com.grpc.area.AreaOrBuilder> 
      getAreaOrBuilderList();
  /**
   * <code>repeated .com.grpc.area.Area area = 5;</code>
   */
  com.grpc.area.AreaOrBuilder getAreaOrBuilder(
      int index);

  /**
   * <code>string zip_code = 6;</code>
   */
  java.lang.String getZipCode();
  /**
   * <code>string zip_code = 6;</code>
   */
  com.google.protobuf.ByteString
      getZipCodeBytes();

  /**
   * <code>string city_code = 7;</code>
   */
  java.lang.String getCityCode();
  /**
   * <code>string city_code = 7;</code>
   */
  com.google.protobuf.ByteString
      getCityCodeBytes();

  /**
   * <code>string name = 8;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 8;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string short_name = 9;</code>
   */
  java.lang.String getShortName();
  /**
   * <code>string short_name = 9;</code>
   */
  com.google.protobuf.ByteString
      getShortNameBytes();

  /**
   * <code>string merger_name = 10;</code>
   */
  java.lang.String getMergerName();
  /**
   * <code>string merger_name = 10;</code>
   */
  com.google.protobuf.ByteString
      getMergerNameBytes();

  /**
   * <code>string pinyin = 11;</code>
   */
  java.lang.String getPinyin();
  /**
   * <code>string pinyin = 11;</code>
   */
  com.google.protobuf.ByteString
      getPinyinBytes();

  /**
   * <code>float lng = 12;</code>
   */
  float getLng();

  /**
   * <code>float lat = 13;</code>
   */
  float getLat();

  /**
   * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
   */
  java.util.List<com.grpc.area.AreaTree> 
      getTreeList();
  /**
   * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
   */
  com.grpc.area.AreaTree getTree(int index);
  /**
   * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
   */
  int getTreeCount();
  /**
   * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
   */
  java.util.List<? extends com.grpc.area.AreaTreeOrBuilder> 
      getTreeOrBuilderList();
  /**
   * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
   */
  com.grpc.area.AreaTreeOrBuilder getTreeOrBuilder(
      int index);
}
