// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role_menu.proto

package com.role_menu.grpc;

/**
 * Protobuf type {@code com.role_menu.grpc.RP}
 */
public  final class RP extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.role_menu.grpc.RP)
    RPOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RP.newBuilder() to construct.
  private RP(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RP() {
    id_ = 0;
    roleId_ = 0;
    menuId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RP(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            roleId_ = input.readInt32();
            break;
          }
          case 16: {

            menuId_ = input.readInt32();
            break;
          }
          case 32: {

            id_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.role_menu.grpc.RoleMenu.internal_static_com_role_menu_grpc_RP_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.role_menu.grpc.RoleMenu.internal_static_com_role_menu_grpc_RP_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.role_menu.grpc.RP.class, com.role_menu.grpc.RP.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 4;
  private int id_;
  /**
   * <code>int32 id = 4;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int ROLE_ID_FIELD_NUMBER = 1;
  private int roleId_;
  /**
   * <code>int32 role_id = 1;</code>
   */
  public int getRoleId() {
    return roleId_;
  }

  public static final int MENU_ID_FIELD_NUMBER = 2;
  private int menuId_;
  /**
   * <code>int32 menu_id = 2;</code>
   */
  public int getMenuId() {
    return menuId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (roleId_ != 0) {
      output.writeInt32(1, roleId_);
    }
    if (menuId_ != 0) {
      output.writeInt32(2, menuId_);
    }
    if (id_ != 0) {
      output.writeInt32(4, id_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (roleId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, roleId_);
    }
    if (menuId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, menuId_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, id_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.role_menu.grpc.RP)) {
      return super.equals(obj);
    }
    com.role_menu.grpc.RP other = (com.role_menu.grpc.RP) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && (getRoleId()
        == other.getRoleId());
    result = result && (getMenuId()
        == other.getMenuId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + ROLE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRoleId();
    hash = (37 * hash) + MENU_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMenuId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.role_menu.grpc.RP parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.role_menu.grpc.RP parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.role_menu.grpc.RP parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.role_menu.grpc.RP parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.role_menu.grpc.RP parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.role_menu.grpc.RP parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.role_menu.grpc.RP parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.role_menu.grpc.RP parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.role_menu.grpc.RP parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.role_menu.grpc.RP parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.role_menu.grpc.RP parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.role_menu.grpc.RP parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.role_menu.grpc.RP prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.role_menu.grpc.RP}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.role_menu.grpc.RP)
      com.role_menu.grpc.RPOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.role_menu.grpc.RoleMenu.internal_static_com_role_menu_grpc_RP_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.role_menu.grpc.RoleMenu.internal_static_com_role_menu_grpc_RP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.role_menu.grpc.RP.class, com.role_menu.grpc.RP.Builder.class);
    }

    // Construct using com.role_menu.grpc.RP.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      roleId_ = 0;

      menuId_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.role_menu.grpc.RoleMenu.internal_static_com_role_menu_grpc_RP_descriptor;
    }

    public com.role_menu.grpc.RP getDefaultInstanceForType() {
      return com.role_menu.grpc.RP.getDefaultInstance();
    }

    public com.role_menu.grpc.RP build() {
      com.role_menu.grpc.RP result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.role_menu.grpc.RP buildPartial() {
      com.role_menu.grpc.RP result = new com.role_menu.grpc.RP(this);
      result.id_ = id_;
      result.roleId_ = roleId_;
      result.menuId_ = menuId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.role_menu.grpc.RP) {
        return mergeFrom((com.role_menu.grpc.RP)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.role_menu.grpc.RP other) {
      if (other == com.role_menu.grpc.RP.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getRoleId() != 0) {
        setRoleId(other.getRoleId());
      }
      if (other.getMenuId() != 0) {
        setMenuId(other.getMenuId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.role_menu.grpc.RP parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.role_menu.grpc.RP) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 4;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 4;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 4;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private int roleId_ ;
    /**
     * <code>int32 role_id = 1;</code>
     */
    public int getRoleId() {
      return roleId_;
    }
    /**
     * <code>int32 role_id = 1;</code>
     */
    public Builder setRoleId(int value) {
      
      roleId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 role_id = 1;</code>
     */
    public Builder clearRoleId() {
      
      roleId_ = 0;
      onChanged();
      return this;
    }

    private int menuId_ ;
    /**
     * <code>int32 menu_id = 2;</code>
     */
    public int getMenuId() {
      return menuId_;
    }
    /**
     * <code>int32 menu_id = 2;</code>
     */
    public Builder setMenuId(int value) {
      
      menuId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 menu_id = 2;</code>
     */
    public Builder clearMenuId() {
      
      menuId_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.role_menu.grpc.RP)
  }

  // @@protoc_insertion_point(class_scope:com.role_menu.grpc.RP)
  private static final com.role_menu.grpc.RP DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.role_menu.grpc.RP();
  }

  public static com.role_menu.grpc.RP getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RP>
      PARSER = new com.google.protobuf.AbstractParser<RP>() {
    public RP parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RP(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RP> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RP> getParserForType() {
    return PARSER;
  }

  public com.role_menu.grpc.RP getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

