// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.grpc.user;

/**
 * Protobuf type {@code com.grpc.user.UserResponse}
 */
public  final class UserResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.grpc.user.UserResponse)
    UserResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserResponse.newBuilder() to construct.
  private UserResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserResponse() {
    id_ = 0;
    name_ = "";
    sex_ = 0;
    nick_ = "";
    salt_ = "";
    phone_ = "";
    email_ = "";
    departid_ = 0;
    statusId_ = 0;
    user_ = java.util.Collections.emptyList();
    areaType_ = "";
    provinceCode_ = "";
    cityCode_ = "";
    countyCode_ = "";
    county_ = "";
    townCode_ = "";
    town_ = "";
    villageCode_ = "";
    mergerName_ = "";
    village_ = "";
    total_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            nick_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            salt_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            phone_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 64: {

            departid_ = input.readInt32();
            break;
          }
          case 72: {

            statusId_ = input.readInt32();
            break;
          }
          case 80: {

            sex_ = input.readInt32();
            break;
          }
          case 90: {
            if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
              user_ = new java.util.ArrayList<com.grpc.user.User>();
              mutable_bitField0_ |= 0x00000200;
            }
            user_.add(
                input.readMessage(com.grpc.user.User.parser(), extensionRegistry));
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            areaType_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            provinceCode_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            cityCode_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            countyCode_ = s;
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            county_ = s;
            break;
          }
          case 138: {
            java.lang.String s = input.readStringRequireUtf8();

            townCode_ = s;
            break;
          }
          case 146: {
            java.lang.String s = input.readStringRequireUtf8();

            town_ = s;
            break;
          }
          case 154: {
            java.lang.String s = input.readStringRequireUtf8();

            villageCode_ = s;
            break;
          }
          case 162: {
            java.lang.String s = input.readStringRequireUtf8();

            mergerName_ = s;
            break;
          }
          case 170: {
            java.lang.String s = input.readStringRequireUtf8();

            village_ = s;
            break;
          }
          case 176: {

            total_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
        user_ = java.util.Collections.unmodifiableList(user_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.user.UserOuterClass.internal_static_com_grpc_user_UserResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.user.UserOuterClass.internal_static_com_grpc_user_UserResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.user.UserResponse.class, com.grpc.user.UserResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEX_FIELD_NUMBER = 10;
  private int sex_;
  /**
   * <code>int32 sex = 10;</code>
   */
  public int getSex() {
    return sex_;
  }

  public static final int NICK_FIELD_NUMBER = 3;
  private volatile java.lang.Object nick_;
  /**
   * <code>string nick = 3;</code>
   */
  public java.lang.String getNick() {
    java.lang.Object ref = nick_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nick_ = s;
      return s;
    }
  }
  /**
   * <code>string nick = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNickBytes() {
    java.lang.Object ref = nick_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nick_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SALT_FIELD_NUMBER = 5;
  private volatile java.lang.Object salt_;
  /**
   * <code>string salt = 5;</code>
   */
  public java.lang.String getSalt() {
    java.lang.Object ref = salt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      salt_ = s;
      return s;
    }
  }
  /**
   * <code>string salt = 5;</code>
   */
  public com.google.protobuf.ByteString
      getSaltBytes() {
    java.lang.Object ref = salt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      salt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONE_FIELD_NUMBER = 6;
  private volatile java.lang.Object phone_;
  /**
   * <code>string phone = 6;</code>
   */
  public java.lang.String getPhone() {
    java.lang.Object ref = phone_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phone_ = s;
      return s;
    }
  }
  /**
   * <code>string phone = 6;</code>
   */
  public com.google.protobuf.ByteString
      getPhoneBytes() {
    java.lang.Object ref = phone_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phone_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 7;
  private volatile java.lang.Object email_;
  /**
   * <code>string email = 7;</code>
   */
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 7;</code>
   */
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPARTID_FIELD_NUMBER = 8;
  private int departid_;
  /**
   * <code>int32 departid = 8;</code>
   */
  public int getDepartid() {
    return departid_;
  }

  public static final int STATUS_ID_FIELD_NUMBER = 9;
  private int statusId_;
  /**
   * <code>int32 status_id = 9;</code>
   */
  public int getStatusId() {
    return statusId_;
  }

  public static final int USER_FIELD_NUMBER = 11;
  private java.util.List<com.grpc.user.User> user_;
  /**
   * <code>repeated .com.grpc.user.User user = 11;</code>
   */
  public java.util.List<com.grpc.user.User> getUserList() {
    return user_;
  }
  /**
   * <code>repeated .com.grpc.user.User user = 11;</code>
   */
  public java.util.List<? extends com.grpc.user.UserOrBuilder> 
      getUserOrBuilderList() {
    return user_;
  }
  /**
   * <code>repeated .com.grpc.user.User user = 11;</code>
   */
  public int getUserCount() {
    return user_.size();
  }
  /**
   * <code>repeated .com.grpc.user.User user = 11;</code>
   */
  public com.grpc.user.User getUser(int index) {
    return user_.get(index);
  }
  /**
   * <code>repeated .com.grpc.user.User user = 11;</code>
   */
  public com.grpc.user.UserOrBuilder getUserOrBuilder(
      int index) {
    return user_.get(index);
  }

  public static final int AREATYPE_FIELD_NUMBER = 12;
  private volatile java.lang.Object areaType_;
  /**
   * <code>string areaType = 12;</code>
   */
  public java.lang.String getAreaType() {
    java.lang.Object ref = areaType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      areaType_ = s;
      return s;
    }
  }
  /**
   * <code>string areaType = 12;</code>
   */
  public com.google.protobuf.ByteString
      getAreaTypeBytes() {
    java.lang.Object ref = areaType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      areaType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROVINCECODE_FIELD_NUMBER = 13;
  private volatile java.lang.Object provinceCode_;
  /**
   * <code>string provinceCode = 13;</code>
   */
  public java.lang.String getProvinceCode() {
    java.lang.Object ref = provinceCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      provinceCode_ = s;
      return s;
    }
  }
  /**
   * <code>string provinceCode = 13;</code>
   */
  public com.google.protobuf.ByteString
      getProvinceCodeBytes() {
    java.lang.Object ref = provinceCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      provinceCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CITYCODE_FIELD_NUMBER = 14;
  private volatile java.lang.Object cityCode_;
  /**
   * <code>string cityCode = 14;</code>
   */
  public java.lang.String getCityCode() {
    java.lang.Object ref = cityCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cityCode_ = s;
      return s;
    }
  }
  /**
   * <code>string cityCode = 14;</code>
   */
  public com.google.protobuf.ByteString
      getCityCodeBytes() {
    java.lang.Object ref = cityCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cityCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNTYCODE_FIELD_NUMBER = 15;
  private volatile java.lang.Object countyCode_;
  /**
   * <code>string countyCode = 15;</code>
   */
  public java.lang.String getCountyCode() {
    java.lang.Object ref = countyCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      countyCode_ = s;
      return s;
    }
  }
  /**
   * <code>string countyCode = 15;</code>
   */
  public com.google.protobuf.ByteString
      getCountyCodeBytes() {
    java.lang.Object ref = countyCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      countyCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNTY_FIELD_NUMBER = 16;
  private volatile java.lang.Object county_;
  /**
   * <code>string county = 16;</code>
   */
  public java.lang.String getCounty() {
    java.lang.Object ref = county_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      county_ = s;
      return s;
    }
  }
  /**
   * <code>string county = 16;</code>
   */
  public com.google.protobuf.ByteString
      getCountyBytes() {
    java.lang.Object ref = county_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      county_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOWNCODE_FIELD_NUMBER = 17;
  private volatile java.lang.Object townCode_;
  /**
   * <code>string townCode = 17;</code>
   */
  public java.lang.String getTownCode() {
    java.lang.Object ref = townCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      townCode_ = s;
      return s;
    }
  }
  /**
   * <code>string townCode = 17;</code>
   */
  public com.google.protobuf.ByteString
      getTownCodeBytes() {
    java.lang.Object ref = townCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      townCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOWN_FIELD_NUMBER = 18;
  private volatile java.lang.Object town_;
  /**
   * <code>string town = 18;</code>
   */
  public java.lang.String getTown() {
    java.lang.Object ref = town_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      town_ = s;
      return s;
    }
  }
  /**
   * <code>string town = 18;</code>
   */
  public com.google.protobuf.ByteString
      getTownBytes() {
    java.lang.Object ref = town_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      town_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VILLAGECODE_FIELD_NUMBER = 19;
  private volatile java.lang.Object villageCode_;
  /**
   * <code>string villageCode = 19;</code>
   */
  public java.lang.String getVillageCode() {
    java.lang.Object ref = villageCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      villageCode_ = s;
      return s;
    }
  }
  /**
   * <code>string villageCode = 19;</code>
   */
  public com.google.protobuf.ByteString
      getVillageCodeBytes() {
    java.lang.Object ref = villageCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      villageCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MERGERNAME_FIELD_NUMBER = 20;
  private volatile java.lang.Object mergerName_;
  /**
   * <code>string mergerName = 20;</code>
   */
  public java.lang.String getMergerName() {
    java.lang.Object ref = mergerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mergerName_ = s;
      return s;
    }
  }
  /**
   * <code>string mergerName = 20;</code>
   */
  public com.google.protobuf.ByteString
      getMergerNameBytes() {
    java.lang.Object ref = mergerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mergerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VILLAGE_FIELD_NUMBER = 21;
  private volatile java.lang.Object village_;
  /**
   * <code>string village = 21;</code>
   */
  public java.lang.String getVillage() {
    java.lang.Object ref = village_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      village_ = s;
      return s;
    }
  }
  /**
   * <code>string village = 21;</code>
   */
  public com.google.protobuf.ByteString
      getVillageBytes() {
    java.lang.Object ref = village_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      village_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_FIELD_NUMBER = 22;
  private int total_;
  /**
   * <code>int32 total = 22;</code>
   */
  public int getTotal() {
    return total_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getNickBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nick_);
    }
    if (!getSaltBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, salt_);
    }
    if (!getPhoneBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, phone_);
    }
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, email_);
    }
    if (departid_ != 0) {
      output.writeInt32(8, departid_);
    }
    if (statusId_ != 0) {
      output.writeInt32(9, statusId_);
    }
    if (sex_ != 0) {
      output.writeInt32(10, sex_);
    }
    for (int i = 0; i < user_.size(); i++) {
      output.writeMessage(11, user_.get(i));
    }
    if (!getAreaTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, areaType_);
    }
    if (!getProvinceCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, provinceCode_);
    }
    if (!getCityCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, cityCode_);
    }
    if (!getCountyCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, countyCode_);
    }
    if (!getCountyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, county_);
    }
    if (!getTownCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 17, townCode_);
    }
    if (!getTownBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 18, town_);
    }
    if (!getVillageCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 19, villageCode_);
    }
    if (!getMergerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 20, mergerName_);
    }
    if (!getVillageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 21, village_);
    }
    if (total_ != 0) {
      output.writeInt32(22, total_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getNickBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nick_);
    }
    if (!getSaltBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, salt_);
    }
    if (!getPhoneBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, phone_);
    }
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, email_);
    }
    if (departid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, departid_);
    }
    if (statusId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, statusId_);
    }
    if (sex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, sex_);
    }
    for (int i = 0; i < user_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, user_.get(i));
    }
    if (!getAreaTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, areaType_);
    }
    if (!getProvinceCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, provinceCode_);
    }
    if (!getCityCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, cityCode_);
    }
    if (!getCountyCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, countyCode_);
    }
    if (!getCountyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, county_);
    }
    if (!getTownCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, townCode_);
    }
    if (!getTownBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, town_);
    }
    if (!getVillageCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, villageCode_);
    }
    if (!getMergerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, mergerName_);
    }
    if (!getVillageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(21, village_);
    }
    if (total_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(22, total_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.user.UserResponse)) {
      return super.equals(obj);
    }
    com.grpc.user.UserResponse other = (com.grpc.user.UserResponse) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && (getSex()
        == other.getSex());
    result = result && getNick()
        .equals(other.getNick());
    result = result && getSalt()
        .equals(other.getSalt());
    result = result && getPhone()
        .equals(other.getPhone());
    result = result && getEmail()
        .equals(other.getEmail());
    result = result && (getDepartid()
        == other.getDepartid());
    result = result && (getStatusId()
        == other.getStatusId());
    result = result && getUserList()
        .equals(other.getUserList());
    result = result && getAreaType()
        .equals(other.getAreaType());
    result = result && getProvinceCode()
        .equals(other.getProvinceCode());
    result = result && getCityCode()
        .equals(other.getCityCode());
    result = result && getCountyCode()
        .equals(other.getCountyCode());
    result = result && getCounty()
        .equals(other.getCounty());
    result = result && getTownCode()
        .equals(other.getTownCode());
    result = result && getTown()
        .equals(other.getTown());
    result = result && getVillageCode()
        .equals(other.getVillageCode());
    result = result && getMergerName()
        .equals(other.getMergerName());
    result = result && getVillage()
        .equals(other.getVillage());
    result = result && (getTotal()
        == other.getTotal());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + SEX_FIELD_NUMBER;
    hash = (53 * hash) + getSex();
    hash = (37 * hash) + NICK_FIELD_NUMBER;
    hash = (53 * hash) + getNick().hashCode();
    hash = (37 * hash) + SALT_FIELD_NUMBER;
    hash = (53 * hash) + getSalt().hashCode();
    hash = (37 * hash) + PHONE_FIELD_NUMBER;
    hash = (53 * hash) + getPhone().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + DEPARTID_FIELD_NUMBER;
    hash = (53 * hash) + getDepartid();
    hash = (37 * hash) + STATUS_ID_FIELD_NUMBER;
    hash = (53 * hash) + getStatusId();
    if (getUserCount() > 0) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUserList().hashCode();
    }
    hash = (37 * hash) + AREATYPE_FIELD_NUMBER;
    hash = (53 * hash) + getAreaType().hashCode();
    hash = (37 * hash) + PROVINCECODE_FIELD_NUMBER;
    hash = (53 * hash) + getProvinceCode().hashCode();
    hash = (37 * hash) + CITYCODE_FIELD_NUMBER;
    hash = (53 * hash) + getCityCode().hashCode();
    hash = (37 * hash) + COUNTYCODE_FIELD_NUMBER;
    hash = (53 * hash) + getCountyCode().hashCode();
    hash = (37 * hash) + COUNTY_FIELD_NUMBER;
    hash = (53 * hash) + getCounty().hashCode();
    hash = (37 * hash) + TOWNCODE_FIELD_NUMBER;
    hash = (53 * hash) + getTownCode().hashCode();
    hash = (37 * hash) + TOWN_FIELD_NUMBER;
    hash = (53 * hash) + getTown().hashCode();
    hash = (37 * hash) + VILLAGECODE_FIELD_NUMBER;
    hash = (53 * hash) + getVillageCode().hashCode();
    hash = (37 * hash) + MERGERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getMergerName().hashCode();
    hash = (37 * hash) + VILLAGE_FIELD_NUMBER;
    hash = (53 * hash) + getVillage().hashCode();
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getTotal();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.user.UserResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.user.UserResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.user.UserResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.user.UserResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.user.UserResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.user.UserResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.user.UserResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.user.UserResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.user.UserResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.user.UserResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.user.UserResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.user.UserResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.user.UserResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.grpc.user.UserResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.grpc.user.UserResponse)
      com.grpc.user.UserResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.user.UserOuterClass.internal_static_com_grpc_user_UserResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.user.UserOuterClass.internal_static_com_grpc_user_UserResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.user.UserResponse.class, com.grpc.user.UserResponse.Builder.class);
    }

    // Construct using com.grpc.user.UserResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUserFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      name_ = "";

      sex_ = 0;

      nick_ = "";

      salt_ = "";

      phone_ = "";

      email_ = "";

      departid_ = 0;

      statusId_ = 0;

      if (userBuilder_ == null) {
        user_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
      } else {
        userBuilder_.clear();
      }
      areaType_ = "";

      provinceCode_ = "";

      cityCode_ = "";

      countyCode_ = "";

      county_ = "";

      townCode_ = "";

      town_ = "";

      villageCode_ = "";

      mergerName_ = "";

      village_ = "";

      total_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.user.UserOuterClass.internal_static_com_grpc_user_UserResponse_descriptor;
    }

    @java.lang.Override
    public com.grpc.user.UserResponse getDefaultInstanceForType() {
      return com.grpc.user.UserResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpc.user.UserResponse build() {
      com.grpc.user.UserResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpc.user.UserResponse buildPartial() {
      com.grpc.user.UserResponse result = new com.grpc.user.UserResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.name_ = name_;
      result.sex_ = sex_;
      result.nick_ = nick_;
      result.salt_ = salt_;
      result.phone_ = phone_;
      result.email_ = email_;
      result.departid_ = departid_;
      result.statusId_ = statusId_;
      if (userBuilder_ == null) {
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          user_ = java.util.Collections.unmodifiableList(user_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      result.areaType_ = areaType_;
      result.provinceCode_ = provinceCode_;
      result.cityCode_ = cityCode_;
      result.countyCode_ = countyCode_;
      result.county_ = county_;
      result.townCode_ = townCode_;
      result.town_ = town_;
      result.villageCode_ = villageCode_;
      result.mergerName_ = mergerName_;
      result.village_ = village_;
      result.total_ = total_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.user.UserResponse) {
        return mergeFrom((com.grpc.user.UserResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.user.UserResponse other) {
      if (other == com.grpc.user.UserResponse.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getSex() != 0) {
        setSex(other.getSex());
      }
      if (!other.getNick().isEmpty()) {
        nick_ = other.nick_;
        onChanged();
      }
      if (!other.getSalt().isEmpty()) {
        salt_ = other.salt_;
        onChanged();
      }
      if (!other.getPhone().isEmpty()) {
        phone_ = other.phone_;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (other.getDepartid() != 0) {
        setDepartid(other.getDepartid());
      }
      if (other.getStatusId() != 0) {
        setStatusId(other.getStatusId());
      }
      if (userBuilder_ == null) {
        if (!other.user_.isEmpty()) {
          if (user_.isEmpty()) {
            user_ = other.user_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureUserIsMutable();
            user_.addAll(other.user_);
          }
          onChanged();
        }
      } else {
        if (!other.user_.isEmpty()) {
          if (userBuilder_.isEmpty()) {
            userBuilder_.dispose();
            userBuilder_ = null;
            user_ = other.user_;
            bitField0_ = (bitField0_ & ~0x00000200);
            userBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUserFieldBuilder() : null;
          } else {
            userBuilder_.addAllMessages(other.user_);
          }
        }
      }
      if (!other.getAreaType().isEmpty()) {
        areaType_ = other.areaType_;
        onChanged();
      }
      if (!other.getProvinceCode().isEmpty()) {
        provinceCode_ = other.provinceCode_;
        onChanged();
      }
      if (!other.getCityCode().isEmpty()) {
        cityCode_ = other.cityCode_;
        onChanged();
      }
      if (!other.getCountyCode().isEmpty()) {
        countyCode_ = other.countyCode_;
        onChanged();
      }
      if (!other.getCounty().isEmpty()) {
        county_ = other.county_;
        onChanged();
      }
      if (!other.getTownCode().isEmpty()) {
        townCode_ = other.townCode_;
        onChanged();
      }
      if (!other.getTown().isEmpty()) {
        town_ = other.town_;
        onChanged();
      }
      if (!other.getVillageCode().isEmpty()) {
        villageCode_ = other.villageCode_;
        onChanged();
      }
      if (!other.getMergerName().isEmpty()) {
        mergerName_ = other.mergerName_;
        onChanged();
      }
      if (!other.getVillage().isEmpty()) {
        village_ = other.village_;
        onChanged();
      }
      if (other.getTotal() != 0) {
        setTotal(other.getTotal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.user.UserResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.user.UserResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int sex_ ;
    /**
     * <code>int32 sex = 10;</code>
     */
    public int getSex() {
      return sex_;
    }
    /**
     * <code>int32 sex = 10;</code>
     */
    public Builder setSex(int value) {
      
      sex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sex = 10;</code>
     */
    public Builder clearSex() {
      
      sex_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object nick_ = "";
    /**
     * <code>string nick = 3;</code>
     */
    public java.lang.String getNick() {
      java.lang.Object ref = nick_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nick_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nick = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNickBytes() {
      java.lang.Object ref = nick_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nick = 3;</code>
     */
    public Builder setNick(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nick_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nick = 3;</code>
     */
    public Builder clearNick() {
      
      nick_ = getDefaultInstance().getNick();
      onChanged();
      return this;
    }
    /**
     * <code>string nick = 3;</code>
     */
    public Builder setNickBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nick_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object salt_ = "";
    /**
     * <code>string salt = 5;</code>
     */
    public java.lang.String getSalt() {
      java.lang.Object ref = salt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        salt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string salt = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSaltBytes() {
      java.lang.Object ref = salt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        salt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string salt = 5;</code>
     */
    public Builder setSalt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      salt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string salt = 5;</code>
     */
    public Builder clearSalt() {
      
      salt_ = getDefaultInstance().getSalt();
      onChanged();
      return this;
    }
    /**
     * <code>string salt = 5;</code>
     */
    public Builder setSaltBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      salt_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object phone_ = "";
    /**
     * <code>string phone = 6;</code>
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string phone = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string phone = 6;</code>
     */
    public Builder setPhone(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      phone_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string phone = 6;</code>
     */
    public Builder clearPhone() {
      
      phone_ = getDefaultInstance().getPhone();
      onChanged();
      return this;
    }
    /**
     * <code>string phone = 6;</code>
     */
    public Builder setPhoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      phone_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 7;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 7;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 7;</code>
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 7;</code>
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string email = 7;</code>
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private int departid_ ;
    /**
     * <code>int32 departid = 8;</code>
     */
    public int getDepartid() {
      return departid_;
    }
    /**
     * <code>int32 departid = 8;</code>
     */
    public Builder setDepartid(int value) {
      
      departid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 departid = 8;</code>
     */
    public Builder clearDepartid() {
      
      departid_ = 0;
      onChanged();
      return this;
    }

    private int statusId_ ;
    /**
     * <code>int32 status_id = 9;</code>
     */
    public int getStatusId() {
      return statusId_;
    }
    /**
     * <code>int32 status_id = 9;</code>
     */
    public Builder setStatusId(int value) {
      
      statusId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 status_id = 9;</code>
     */
    public Builder clearStatusId() {
      
      statusId_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.grpc.user.User> user_ =
      java.util.Collections.emptyList();
    private void ensureUserIsMutable() {
      if (!((bitField0_ & 0x00000200) == 0x00000200)) {
        user_ = new java.util.ArrayList<com.grpc.user.User>(user_);
        bitField0_ |= 0x00000200;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.user.User, com.grpc.user.User.Builder, com.grpc.user.UserOrBuilder> userBuilder_;

    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public java.util.List<com.grpc.user.User> getUserList() {
      if (userBuilder_ == null) {
        return java.util.Collections.unmodifiableList(user_);
      } else {
        return userBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public int getUserCount() {
      if (userBuilder_ == null) {
        return user_.size();
      } else {
        return userBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public com.grpc.user.User getUser(int index) {
      if (userBuilder_ == null) {
        return user_.get(index);
      } else {
        return userBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public Builder setUser(
        int index, com.grpc.user.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserIsMutable();
        user_.set(index, value);
        onChanged();
      } else {
        userBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public Builder setUser(
        int index, com.grpc.user.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        ensureUserIsMutable();
        user_.set(index, builderForValue.build());
        onChanged();
      } else {
        userBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public Builder addUser(com.grpc.user.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserIsMutable();
        user_.add(value);
        onChanged();
      } else {
        userBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public Builder addUser(
        int index, com.grpc.user.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserIsMutable();
        user_.add(index, value);
        onChanged();
      } else {
        userBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public Builder addUser(
        com.grpc.user.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        ensureUserIsMutable();
        user_.add(builderForValue.build());
        onChanged();
      } else {
        userBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public Builder addUser(
        int index, com.grpc.user.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        ensureUserIsMutable();
        user_.add(index, builderForValue.build());
        onChanged();
      } else {
        userBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public Builder addAllUser(
        java.lang.Iterable<? extends com.grpc.user.User> values) {
      if (userBuilder_ == null) {
        ensureUserIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, user_);
        onChanged();
      } else {
        userBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
      } else {
        userBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public Builder removeUser(int index) {
      if (userBuilder_ == null) {
        ensureUserIsMutable();
        user_.remove(index);
        onChanged();
      } else {
        userBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public com.grpc.user.User.Builder getUserBuilder(
        int index) {
      return getUserFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public com.grpc.user.UserOrBuilder getUserOrBuilder(
        int index) {
      if (userBuilder_ == null) {
        return user_.get(index);  } else {
        return userBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public java.util.List<? extends com.grpc.user.UserOrBuilder> 
         getUserOrBuilderList() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(user_);
      }
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public com.grpc.user.User.Builder addUserBuilder() {
      return getUserFieldBuilder().addBuilder(
          com.grpc.user.User.getDefaultInstance());
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public com.grpc.user.User.Builder addUserBuilder(
        int index) {
      return getUserFieldBuilder().addBuilder(
          index, com.grpc.user.User.getDefaultInstance());
    }
    /**
     * <code>repeated .com.grpc.user.User user = 11;</code>
     */
    public java.util.List<com.grpc.user.User.Builder> 
         getUserBuilderList() {
      return getUserFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.user.User, com.grpc.user.User.Builder, com.grpc.user.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.grpc.user.User, com.grpc.user.User.Builder, com.grpc.user.UserOrBuilder>(
                user_,
                ((bitField0_ & 0x00000200) == 0x00000200),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private java.lang.Object areaType_ = "";
    /**
     * <code>string areaType = 12;</code>
     */
    public java.lang.String getAreaType() {
      java.lang.Object ref = areaType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        areaType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string areaType = 12;</code>
     */
    public com.google.protobuf.ByteString
        getAreaTypeBytes() {
      java.lang.Object ref = areaType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        areaType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string areaType = 12;</code>
     */
    public Builder setAreaType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      areaType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string areaType = 12;</code>
     */
    public Builder clearAreaType() {
      
      areaType_ = getDefaultInstance().getAreaType();
      onChanged();
      return this;
    }
    /**
     * <code>string areaType = 12;</code>
     */
    public Builder setAreaTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      areaType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object provinceCode_ = "";
    /**
     * <code>string provinceCode = 13;</code>
     */
    public java.lang.String getProvinceCode() {
      java.lang.Object ref = provinceCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        provinceCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string provinceCode = 13;</code>
     */
    public com.google.protobuf.ByteString
        getProvinceCodeBytes() {
      java.lang.Object ref = provinceCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        provinceCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string provinceCode = 13;</code>
     */
    public Builder setProvinceCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      provinceCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string provinceCode = 13;</code>
     */
    public Builder clearProvinceCode() {
      
      provinceCode_ = getDefaultInstance().getProvinceCode();
      onChanged();
      return this;
    }
    /**
     * <code>string provinceCode = 13;</code>
     */
    public Builder setProvinceCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      provinceCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cityCode_ = "";
    /**
     * <code>string cityCode = 14;</code>
     */
    public java.lang.String getCityCode() {
      java.lang.Object ref = cityCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cityCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cityCode = 14;</code>
     */
    public com.google.protobuf.ByteString
        getCityCodeBytes() {
      java.lang.Object ref = cityCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cityCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cityCode = 14;</code>
     */
    public Builder setCityCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cityCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cityCode = 14;</code>
     */
    public Builder clearCityCode() {
      
      cityCode_ = getDefaultInstance().getCityCode();
      onChanged();
      return this;
    }
    /**
     * <code>string cityCode = 14;</code>
     */
    public Builder setCityCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cityCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object countyCode_ = "";
    /**
     * <code>string countyCode = 15;</code>
     */
    public java.lang.String getCountyCode() {
      java.lang.Object ref = countyCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countyCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string countyCode = 15;</code>
     */
    public com.google.protobuf.ByteString
        getCountyCodeBytes() {
      java.lang.Object ref = countyCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string countyCode = 15;</code>
     */
    public Builder setCountyCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      countyCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string countyCode = 15;</code>
     */
    public Builder clearCountyCode() {
      
      countyCode_ = getDefaultInstance().getCountyCode();
      onChanged();
      return this;
    }
    /**
     * <code>string countyCode = 15;</code>
     */
    public Builder setCountyCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      countyCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object county_ = "";
    /**
     * <code>string county = 16;</code>
     */
    public java.lang.String getCounty() {
      java.lang.Object ref = county_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        county_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string county = 16;</code>
     */
    public com.google.protobuf.ByteString
        getCountyBytes() {
      java.lang.Object ref = county_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        county_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string county = 16;</code>
     */
    public Builder setCounty(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      county_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string county = 16;</code>
     */
    public Builder clearCounty() {
      
      county_ = getDefaultInstance().getCounty();
      onChanged();
      return this;
    }
    /**
     * <code>string county = 16;</code>
     */
    public Builder setCountyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      county_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object townCode_ = "";
    /**
     * <code>string townCode = 17;</code>
     */
    public java.lang.String getTownCode() {
      java.lang.Object ref = townCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        townCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string townCode = 17;</code>
     */
    public com.google.protobuf.ByteString
        getTownCodeBytes() {
      java.lang.Object ref = townCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        townCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string townCode = 17;</code>
     */
    public Builder setTownCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      townCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string townCode = 17;</code>
     */
    public Builder clearTownCode() {
      
      townCode_ = getDefaultInstance().getTownCode();
      onChanged();
      return this;
    }
    /**
     * <code>string townCode = 17;</code>
     */
    public Builder setTownCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      townCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object town_ = "";
    /**
     * <code>string town = 18;</code>
     */
    public java.lang.String getTown() {
      java.lang.Object ref = town_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        town_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string town = 18;</code>
     */
    public com.google.protobuf.ByteString
        getTownBytes() {
      java.lang.Object ref = town_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        town_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string town = 18;</code>
     */
    public Builder setTown(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      town_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string town = 18;</code>
     */
    public Builder clearTown() {
      
      town_ = getDefaultInstance().getTown();
      onChanged();
      return this;
    }
    /**
     * <code>string town = 18;</code>
     */
    public Builder setTownBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      town_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object villageCode_ = "";
    /**
     * <code>string villageCode = 19;</code>
     */
    public java.lang.String getVillageCode() {
      java.lang.Object ref = villageCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        villageCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string villageCode = 19;</code>
     */
    public com.google.protobuf.ByteString
        getVillageCodeBytes() {
      java.lang.Object ref = villageCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        villageCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string villageCode = 19;</code>
     */
    public Builder setVillageCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      villageCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string villageCode = 19;</code>
     */
    public Builder clearVillageCode() {
      
      villageCode_ = getDefaultInstance().getVillageCode();
      onChanged();
      return this;
    }
    /**
     * <code>string villageCode = 19;</code>
     */
    public Builder setVillageCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      villageCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mergerName_ = "";
    /**
     * <code>string mergerName = 20;</code>
     */
    public java.lang.String getMergerName() {
      java.lang.Object ref = mergerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mergerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mergerName = 20;</code>
     */
    public com.google.protobuf.ByteString
        getMergerNameBytes() {
      java.lang.Object ref = mergerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mergerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mergerName = 20;</code>
     */
    public Builder setMergerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mergerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mergerName = 20;</code>
     */
    public Builder clearMergerName() {
      
      mergerName_ = getDefaultInstance().getMergerName();
      onChanged();
      return this;
    }
    /**
     * <code>string mergerName = 20;</code>
     */
    public Builder setMergerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mergerName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object village_ = "";
    /**
     * <code>string village = 21;</code>
     */
    public java.lang.String getVillage() {
      java.lang.Object ref = village_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        village_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string village = 21;</code>
     */
    public com.google.protobuf.ByteString
        getVillageBytes() {
      java.lang.Object ref = village_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        village_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string village = 21;</code>
     */
    public Builder setVillage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      village_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string village = 21;</code>
     */
    public Builder clearVillage() {
      
      village_ = getDefaultInstance().getVillage();
      onChanged();
      return this;
    }
    /**
     * <code>string village = 21;</code>
     */
    public Builder setVillageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      village_ = value;
      onChanged();
      return this;
    }

    private int total_ ;
    /**
     * <code>int32 total = 22;</code>
     */
    public int getTotal() {
      return total_;
    }
    /**
     * <code>int32 total = 22;</code>
     */
    public Builder setTotal(int value) {
      
      total_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total = 22;</code>
     */
    public Builder clearTotal() {
      
      total_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.grpc.user.UserResponse)
  }

  // @@protoc_insertion_point(class_scope:com.grpc.user.UserResponse)
  private static final com.grpc.user.UserResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.user.UserResponse();
  }

  public static com.grpc.user.UserResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserResponse>
      PARSER = new com.google.protobuf.AbstractParser<UserResponse>() {
    @java.lang.Override
    public UserResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpc.user.UserResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

