// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group.proto

package com.grpc.group;

public interface GroupResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.group.GroupResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string avatar = 3;</code>
   */
  java.lang.String getAvatar();
  /**
   * <code>string avatar = 3;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <code>int32 creator = 4;</code>
   */
  int getCreator();

  /**
   * <code>repeated .com.grpc.group.Group group = 5;</code>
   */
  java.util.List<com.grpc.group.Group> 
      getGroupList();
  /**
   * <code>repeated .com.grpc.group.Group group = 5;</code>
   */
  com.grpc.group.Group getGroup(int index);
  /**
   * <code>repeated .com.grpc.group.Group group = 5;</code>
   */
  int getGroupCount();
  /**
   * <code>repeated .com.grpc.group.Group group = 5;</code>
   */
  java.util.List<? extends com.grpc.group.GroupOrBuilder> 
      getGroupOrBuilderList();
  /**
   * <code>repeated .com.grpc.group.Group group = 5;</code>
   */
  com.grpc.group.GroupOrBuilder getGroupOrBuilder(
      int index);

  /**
   * <code>int32 status_id = 6;</code>
   */
  int getStatusId();

  /**
   * <code>int32 userCnt = 7;</code>
   */
  int getUserCnt();
}
