// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group.proto

package com.grpc.group;

public final class GroupOuterClass {
  private GroupOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_proto_group_grpc_Group_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_proto_group_grpc_Group_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_proto_group_grpc_GroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_proto_group_grpc_GroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_proto_group_grpc_GroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_proto_group_grpc_GroupResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013group.proto\022\024com.proto.group.grpc\"u\n\005G" +
      "roup\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\017\n\007creato" +
      "r\030\003 \001(\005\022\017\n\007userCnt\030\004 \001(\005\022\016\n\006status\030\005 \001(\005" +
      "\022\017\n\007updated\030\006 \001(\005\022\017\n\007created\030\007 \001(\005\"v\n\014Gr" +
      "oupRequest\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\017\n\007" +
      "creator\030\003 \001(\005\022\017\n\007userCnt\030\004 \001(\005\022*\n\005group\030" +
      "\005 \003(\0132\033.com.proto.group.grpc.Group\"\212\001\n\rG" +
      "roupResponse\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\017" +
      "\n\007creator\030\003 \001(\005\022\017\n\007userCnt\030\004 \001(\005\022\021\n\tstat" +
      "us_id\030\005 \001(\005\022*\n\005group\030\006 \003(\0132\033.com.proto.g" +
      "roup.grpc.Group2\351\002\n\014GroupService\022T\n\tlist" +
      "Group\022\".com.proto.group.grpc.GroupReques" +
      "t\032#.com.proto.group.grpc.GroupResponse\022S" +
      "\n\010addGroup\022\".com.proto.group.grpc.GroupR" +
      "equest\032#.com.proto.group.grpc.GroupRespo" +
      "nse\022V\n\013removeGroup\022\".com.proto.group.grp" +
      "c.GroupRequest\032#.com.proto.group.grpc.Gr" +
      "oupResponse\022V\n\013modifyGroup\022\".com.proto.g" +
      "roup.grpc.GroupRequest\032#.com.proto.group" +
      ".grpc.GroupResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_proto_group_grpc_Group_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_proto_group_grpc_Group_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_proto_group_grpc_Group_descriptor,
        new java.lang.String[] { "Id", "Name", "Creator", "UserCnt", "Status", "Updated", "Created", });
    internal_static_com_proto_group_grpc_GroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_proto_group_grpc_GroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_proto_group_grpc_GroupRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Creator", "UserCnt", "Group", });
    internal_static_com_proto_group_grpc_GroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_proto_group_grpc_GroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_proto_group_grpc_GroupResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Creator", "UserCnt", "StatusId", "Group", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
