// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: area.proto

package com.grpc.area;

/**
 * Protobuf type {@code com.grpc.area.AreaResponse}
 */
public  final class AreaResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.grpc.area.AreaResponse)
    AreaResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AreaResponse.newBuilder() to construct.
  private AreaResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AreaResponse() {
    id_ = 0;
    levelCode_ = 0;
    parentCode_ = "";
    areaCode_ = "";
    area_ = java.util.Collections.emptyList();
    zipCode_ = "";
    cityCode_ = "";
    name_ = "";
    shortName_ = "";
    mergerName_ = "";
    pinyin_ = "";
    lng_ = 0F;
    lat_ = 0F;
    tree_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AreaResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 16: {

            levelCode_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            parentCode_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            areaCode_ = s;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              area_ = new java.util.ArrayList<com.grpc.area.Area>();
              mutable_bitField0_ |= 0x00000010;
            }
            area_.add(
                input.readMessage(com.grpc.area.Area.parser(), extensionRegistry));
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            zipCode_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            cityCode_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            shortName_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            mergerName_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            pinyin_ = s;
            break;
          }
          case 101: {

            lng_ = input.readFloat();
            break;
          }
          case 109: {

            lat_ = input.readFloat();
            break;
          }
          case 162: {
            if (!((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
              tree_ = new java.util.ArrayList<com.grpc.area.AreaTree>();
              mutable_bitField0_ |= 0x00002000;
            }
            tree_.add(
                input.readMessage(com.grpc.area.AreaTree.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        area_ = java.util.Collections.unmodifiableList(area_);
      }
      if (((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
        tree_ = java.util.Collections.unmodifiableList(tree_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.area.AreaOuterClass.internal_static_com_grpc_area_AreaResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.area.AreaOuterClass.internal_static_com_grpc_area_AreaResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.area.AreaResponse.class, com.grpc.area.AreaResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int LEVEL_CODE_FIELD_NUMBER = 2;
  private int levelCode_;
  /**
   * <code>int32 level_code = 2;</code>
   */
  public int getLevelCode() {
    return levelCode_;
  }

  public static final int PARENT_CODE_FIELD_NUMBER = 3;
  private volatile java.lang.Object parentCode_;
  /**
   * <code>string parent_code = 3;</code>
   */
  public java.lang.String getParentCode() {
    java.lang.Object ref = parentCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parentCode_ = s;
      return s;
    }
  }
  /**
   * <code>string parent_code = 3;</code>
   */
  public com.google.protobuf.ByteString
      getParentCodeBytes() {
    java.lang.Object ref = parentCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parentCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AREA_CODE_FIELD_NUMBER = 4;
  private volatile java.lang.Object areaCode_;
  /**
   * <code>string area_code = 4;</code>
   */
  public java.lang.String getAreaCode() {
    java.lang.Object ref = areaCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      areaCode_ = s;
      return s;
    }
  }
  /**
   * <code>string area_code = 4;</code>
   */
  public com.google.protobuf.ByteString
      getAreaCodeBytes() {
    java.lang.Object ref = areaCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      areaCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AREA_FIELD_NUMBER = 5;
  private java.util.List<com.grpc.area.Area> area_;
  /**
   * <code>repeated .com.grpc.area.Area area = 5;</code>
   */
  public java.util.List<com.grpc.area.Area> getAreaList() {
    return area_;
  }
  /**
   * <code>repeated .com.grpc.area.Area area = 5;</code>
   */
  public java.util.List<? extends com.grpc.area.AreaOrBuilder> 
      getAreaOrBuilderList() {
    return area_;
  }
  /**
   * <code>repeated .com.grpc.area.Area area = 5;</code>
   */
  public int getAreaCount() {
    return area_.size();
  }
  /**
   * <code>repeated .com.grpc.area.Area area = 5;</code>
   */
  public com.grpc.area.Area getArea(int index) {
    return area_.get(index);
  }
  /**
   * <code>repeated .com.grpc.area.Area area = 5;</code>
   */
  public com.grpc.area.AreaOrBuilder getAreaOrBuilder(
      int index) {
    return area_.get(index);
  }

  public static final int ZIP_CODE_FIELD_NUMBER = 6;
  private volatile java.lang.Object zipCode_;
  /**
   * <code>string zip_code = 6;</code>
   */
  public java.lang.String getZipCode() {
    java.lang.Object ref = zipCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      zipCode_ = s;
      return s;
    }
  }
  /**
   * <code>string zip_code = 6;</code>
   */
  public com.google.protobuf.ByteString
      getZipCodeBytes() {
    java.lang.Object ref = zipCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      zipCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CITY_CODE_FIELD_NUMBER = 7;
  private volatile java.lang.Object cityCode_;
  /**
   * <code>string city_code = 7;</code>
   */
  public java.lang.String getCityCode() {
    java.lang.Object ref = cityCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cityCode_ = s;
      return s;
    }
  }
  /**
   * <code>string city_code = 7;</code>
   */
  public com.google.protobuf.ByteString
      getCityCodeBytes() {
    java.lang.Object ref = cityCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cityCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 8;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 8;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 8;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHORT_NAME_FIELD_NUMBER = 9;
  private volatile java.lang.Object shortName_;
  /**
   * <code>string short_name = 9;</code>
   */
  public java.lang.String getShortName() {
    java.lang.Object ref = shortName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      shortName_ = s;
      return s;
    }
  }
  /**
   * <code>string short_name = 9;</code>
   */
  public com.google.protobuf.ByteString
      getShortNameBytes() {
    java.lang.Object ref = shortName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      shortName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MERGER_NAME_FIELD_NUMBER = 10;
  private volatile java.lang.Object mergerName_;
  /**
   * <code>string merger_name = 10;</code>
   */
  public java.lang.String getMergerName() {
    java.lang.Object ref = mergerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mergerName_ = s;
      return s;
    }
  }
  /**
   * <code>string merger_name = 10;</code>
   */
  public com.google.protobuf.ByteString
      getMergerNameBytes() {
    java.lang.Object ref = mergerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mergerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PINYIN_FIELD_NUMBER = 11;
  private volatile java.lang.Object pinyin_;
  /**
   * <code>string pinyin = 11;</code>
   */
  public java.lang.String getPinyin() {
    java.lang.Object ref = pinyin_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pinyin_ = s;
      return s;
    }
  }
  /**
   * <code>string pinyin = 11;</code>
   */
  public com.google.protobuf.ByteString
      getPinyinBytes() {
    java.lang.Object ref = pinyin_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pinyin_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LNG_FIELD_NUMBER = 12;
  private float lng_;
  /**
   * <code>float lng = 12;</code>
   */
  public float getLng() {
    return lng_;
  }

  public static final int LAT_FIELD_NUMBER = 13;
  private float lat_;
  /**
   * <code>float lat = 13;</code>
   */
  public float getLat() {
    return lat_;
  }

  public static final int TREE_FIELD_NUMBER = 20;
  private java.util.List<com.grpc.area.AreaTree> tree_;
  /**
   * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
   */
  public java.util.List<com.grpc.area.AreaTree> getTreeList() {
    return tree_;
  }
  /**
   * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
   */
  public java.util.List<? extends com.grpc.area.AreaTreeOrBuilder> 
      getTreeOrBuilderList() {
    return tree_;
  }
  /**
   * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
   */
  public int getTreeCount() {
    return tree_.size();
  }
  /**
   * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
   */
  public com.grpc.area.AreaTree getTree(int index) {
    return tree_.get(index);
  }
  /**
   * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
   */
  public com.grpc.area.AreaTreeOrBuilder getTreeOrBuilder(
      int index) {
    return tree_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (levelCode_ != 0) {
      output.writeInt32(2, levelCode_);
    }
    if (!getParentCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, parentCode_);
    }
    if (!getAreaCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, areaCode_);
    }
    for (int i = 0; i < area_.size(); i++) {
      output.writeMessage(5, area_.get(i));
    }
    if (!getZipCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, zipCode_);
    }
    if (!getCityCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, cityCode_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, name_);
    }
    if (!getShortNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, shortName_);
    }
    if (!getMergerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, mergerName_);
    }
    if (!getPinyinBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, pinyin_);
    }
    if (lng_ != 0F) {
      output.writeFloat(12, lng_);
    }
    if (lat_ != 0F) {
      output.writeFloat(13, lat_);
    }
    for (int i = 0; i < tree_.size(); i++) {
      output.writeMessage(20, tree_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (levelCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, levelCode_);
    }
    if (!getParentCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, parentCode_);
    }
    if (!getAreaCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, areaCode_);
    }
    for (int i = 0; i < area_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, area_.get(i));
    }
    if (!getZipCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, zipCode_);
    }
    if (!getCityCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, cityCode_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, name_);
    }
    if (!getShortNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, shortName_);
    }
    if (!getMergerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, mergerName_);
    }
    if (!getPinyinBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, pinyin_);
    }
    if (lng_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(12, lng_);
    }
    if (lat_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(13, lat_);
    }
    for (int i = 0; i < tree_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, tree_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.area.AreaResponse)) {
      return super.equals(obj);
    }
    com.grpc.area.AreaResponse other = (com.grpc.area.AreaResponse) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && (getLevelCode()
        == other.getLevelCode());
    result = result && getParentCode()
        .equals(other.getParentCode());
    result = result && getAreaCode()
        .equals(other.getAreaCode());
    result = result && getAreaList()
        .equals(other.getAreaList());
    result = result && getZipCode()
        .equals(other.getZipCode());
    result = result && getCityCode()
        .equals(other.getCityCode());
    result = result && getName()
        .equals(other.getName());
    result = result && getShortName()
        .equals(other.getShortName());
    result = result && getMergerName()
        .equals(other.getMergerName());
    result = result && getPinyin()
        .equals(other.getPinyin());
    result = result && (
        java.lang.Float.floatToIntBits(getLng())
        == java.lang.Float.floatToIntBits(
            other.getLng()));
    result = result && (
        java.lang.Float.floatToIntBits(getLat())
        == java.lang.Float.floatToIntBits(
            other.getLat()));
    result = result && getTreeList()
        .equals(other.getTreeList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + LEVEL_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getLevelCode();
    hash = (37 * hash) + PARENT_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getParentCode().hashCode();
    hash = (37 * hash) + AREA_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getAreaCode().hashCode();
    if (getAreaCount() > 0) {
      hash = (37 * hash) + AREA_FIELD_NUMBER;
      hash = (53 * hash) + getAreaList().hashCode();
    }
    hash = (37 * hash) + ZIP_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getZipCode().hashCode();
    hash = (37 * hash) + CITY_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCityCode().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + SHORT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getShortName().hashCode();
    hash = (37 * hash) + MERGER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getMergerName().hashCode();
    hash = (37 * hash) + PINYIN_FIELD_NUMBER;
    hash = (53 * hash) + getPinyin().hashCode();
    hash = (37 * hash) + LNG_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getLng());
    hash = (37 * hash) + LAT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getLat());
    if (getTreeCount() > 0) {
      hash = (37 * hash) + TREE_FIELD_NUMBER;
      hash = (53 * hash) + getTreeList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.area.AreaResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.area.AreaResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.area.AreaResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.area.AreaResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.area.AreaResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.area.AreaResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.area.AreaResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.area.AreaResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.area.AreaResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.area.AreaResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.area.AreaResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.area.AreaResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.area.AreaResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.grpc.area.AreaResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.grpc.area.AreaResponse)
      com.grpc.area.AreaResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.area.AreaOuterClass.internal_static_com_grpc_area_AreaResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.area.AreaOuterClass.internal_static_com_grpc_area_AreaResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.area.AreaResponse.class, com.grpc.area.AreaResponse.Builder.class);
    }

    // Construct using com.grpc.area.AreaResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAreaFieldBuilder();
        getTreeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      levelCode_ = 0;

      parentCode_ = "";

      areaCode_ = "";

      if (areaBuilder_ == null) {
        area_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        areaBuilder_.clear();
      }
      zipCode_ = "";

      cityCode_ = "";

      name_ = "";

      shortName_ = "";

      mergerName_ = "";

      pinyin_ = "";

      lng_ = 0F;

      lat_ = 0F;

      if (treeBuilder_ == null) {
        tree_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
      } else {
        treeBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.area.AreaOuterClass.internal_static_com_grpc_area_AreaResponse_descriptor;
    }

    @java.lang.Override
    public com.grpc.area.AreaResponse getDefaultInstanceForType() {
      return com.grpc.area.AreaResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpc.area.AreaResponse build() {
      com.grpc.area.AreaResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpc.area.AreaResponse buildPartial() {
      com.grpc.area.AreaResponse result = new com.grpc.area.AreaResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.levelCode_ = levelCode_;
      result.parentCode_ = parentCode_;
      result.areaCode_ = areaCode_;
      if (areaBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          area_ = java.util.Collections.unmodifiableList(area_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.area_ = area_;
      } else {
        result.area_ = areaBuilder_.build();
      }
      result.zipCode_ = zipCode_;
      result.cityCode_ = cityCode_;
      result.name_ = name_;
      result.shortName_ = shortName_;
      result.mergerName_ = mergerName_;
      result.pinyin_ = pinyin_;
      result.lng_ = lng_;
      result.lat_ = lat_;
      if (treeBuilder_ == null) {
        if (((bitField0_ & 0x00002000) == 0x00002000)) {
          tree_ = java.util.Collections.unmodifiableList(tree_);
          bitField0_ = (bitField0_ & ~0x00002000);
        }
        result.tree_ = tree_;
      } else {
        result.tree_ = treeBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.area.AreaResponse) {
        return mergeFrom((com.grpc.area.AreaResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.area.AreaResponse other) {
      if (other == com.grpc.area.AreaResponse.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getLevelCode() != 0) {
        setLevelCode(other.getLevelCode());
      }
      if (!other.getParentCode().isEmpty()) {
        parentCode_ = other.parentCode_;
        onChanged();
      }
      if (!other.getAreaCode().isEmpty()) {
        areaCode_ = other.areaCode_;
        onChanged();
      }
      if (areaBuilder_ == null) {
        if (!other.area_.isEmpty()) {
          if (area_.isEmpty()) {
            area_ = other.area_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureAreaIsMutable();
            area_.addAll(other.area_);
          }
          onChanged();
        }
      } else {
        if (!other.area_.isEmpty()) {
          if (areaBuilder_.isEmpty()) {
            areaBuilder_.dispose();
            areaBuilder_ = null;
            area_ = other.area_;
            bitField0_ = (bitField0_ & ~0x00000010);
            areaBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAreaFieldBuilder() : null;
          } else {
            areaBuilder_.addAllMessages(other.area_);
          }
        }
      }
      if (!other.getZipCode().isEmpty()) {
        zipCode_ = other.zipCode_;
        onChanged();
      }
      if (!other.getCityCode().isEmpty()) {
        cityCode_ = other.cityCode_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getShortName().isEmpty()) {
        shortName_ = other.shortName_;
        onChanged();
      }
      if (!other.getMergerName().isEmpty()) {
        mergerName_ = other.mergerName_;
        onChanged();
      }
      if (!other.getPinyin().isEmpty()) {
        pinyin_ = other.pinyin_;
        onChanged();
      }
      if (other.getLng() != 0F) {
        setLng(other.getLng());
      }
      if (other.getLat() != 0F) {
        setLat(other.getLat());
      }
      if (treeBuilder_ == null) {
        if (!other.tree_.isEmpty()) {
          if (tree_.isEmpty()) {
            tree_ = other.tree_;
            bitField0_ = (bitField0_ & ~0x00002000);
          } else {
            ensureTreeIsMutable();
            tree_.addAll(other.tree_);
          }
          onChanged();
        }
      } else {
        if (!other.tree_.isEmpty()) {
          if (treeBuilder_.isEmpty()) {
            treeBuilder_.dispose();
            treeBuilder_ = null;
            tree_ = other.tree_;
            bitField0_ = (bitField0_ & ~0x00002000);
            treeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTreeFieldBuilder() : null;
          } else {
            treeBuilder_.addAllMessages(other.tree_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.area.AreaResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.area.AreaResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private int levelCode_ ;
    /**
     * <code>int32 level_code = 2;</code>
     */
    public int getLevelCode() {
      return levelCode_;
    }
    /**
     * <code>int32 level_code = 2;</code>
     */
    public Builder setLevelCode(int value) {
      
      levelCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 level_code = 2;</code>
     */
    public Builder clearLevelCode() {
      
      levelCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object parentCode_ = "";
    /**
     * <code>string parent_code = 3;</code>
     */
    public java.lang.String getParentCode() {
      java.lang.Object ref = parentCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string parent_code = 3;</code>
     */
    public com.google.protobuf.ByteString
        getParentCodeBytes() {
      java.lang.Object ref = parentCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string parent_code = 3;</code>
     */
    public Builder setParentCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      parentCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string parent_code = 3;</code>
     */
    public Builder clearParentCode() {
      
      parentCode_ = getDefaultInstance().getParentCode();
      onChanged();
      return this;
    }
    /**
     * <code>string parent_code = 3;</code>
     */
    public Builder setParentCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      parentCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object areaCode_ = "";
    /**
     * <code>string area_code = 4;</code>
     */
    public java.lang.String getAreaCode() {
      java.lang.Object ref = areaCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        areaCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string area_code = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAreaCodeBytes() {
      java.lang.Object ref = areaCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        areaCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string area_code = 4;</code>
     */
    public Builder setAreaCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      areaCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string area_code = 4;</code>
     */
    public Builder clearAreaCode() {
      
      areaCode_ = getDefaultInstance().getAreaCode();
      onChanged();
      return this;
    }
    /**
     * <code>string area_code = 4;</code>
     */
    public Builder setAreaCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      areaCode_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.grpc.area.Area> area_ =
      java.util.Collections.emptyList();
    private void ensureAreaIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        area_ = new java.util.ArrayList<com.grpc.area.Area>(area_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.area.Area, com.grpc.area.Area.Builder, com.grpc.area.AreaOrBuilder> areaBuilder_;

    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public java.util.List<com.grpc.area.Area> getAreaList() {
      if (areaBuilder_ == null) {
        return java.util.Collections.unmodifiableList(area_);
      } else {
        return areaBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public int getAreaCount() {
      if (areaBuilder_ == null) {
        return area_.size();
      } else {
        return areaBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public com.grpc.area.Area getArea(int index) {
      if (areaBuilder_ == null) {
        return area_.get(index);
      } else {
        return areaBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public Builder setArea(
        int index, com.grpc.area.Area value) {
      if (areaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAreaIsMutable();
        area_.set(index, value);
        onChanged();
      } else {
        areaBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public Builder setArea(
        int index, com.grpc.area.Area.Builder builderForValue) {
      if (areaBuilder_ == null) {
        ensureAreaIsMutable();
        area_.set(index, builderForValue.build());
        onChanged();
      } else {
        areaBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public Builder addArea(com.grpc.area.Area value) {
      if (areaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAreaIsMutable();
        area_.add(value);
        onChanged();
      } else {
        areaBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public Builder addArea(
        int index, com.grpc.area.Area value) {
      if (areaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAreaIsMutable();
        area_.add(index, value);
        onChanged();
      } else {
        areaBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public Builder addArea(
        com.grpc.area.Area.Builder builderForValue) {
      if (areaBuilder_ == null) {
        ensureAreaIsMutable();
        area_.add(builderForValue.build());
        onChanged();
      } else {
        areaBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public Builder addArea(
        int index, com.grpc.area.Area.Builder builderForValue) {
      if (areaBuilder_ == null) {
        ensureAreaIsMutable();
        area_.add(index, builderForValue.build());
        onChanged();
      } else {
        areaBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public Builder addAllArea(
        java.lang.Iterable<? extends com.grpc.area.Area> values) {
      if (areaBuilder_ == null) {
        ensureAreaIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, area_);
        onChanged();
      } else {
        areaBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public Builder clearArea() {
      if (areaBuilder_ == null) {
        area_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        areaBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public Builder removeArea(int index) {
      if (areaBuilder_ == null) {
        ensureAreaIsMutable();
        area_.remove(index);
        onChanged();
      } else {
        areaBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public com.grpc.area.Area.Builder getAreaBuilder(
        int index) {
      return getAreaFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public com.grpc.area.AreaOrBuilder getAreaOrBuilder(
        int index) {
      if (areaBuilder_ == null) {
        return area_.get(index);  } else {
        return areaBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public java.util.List<? extends com.grpc.area.AreaOrBuilder> 
         getAreaOrBuilderList() {
      if (areaBuilder_ != null) {
        return areaBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(area_);
      }
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public com.grpc.area.Area.Builder addAreaBuilder() {
      return getAreaFieldBuilder().addBuilder(
          com.grpc.area.Area.getDefaultInstance());
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public com.grpc.area.Area.Builder addAreaBuilder(
        int index) {
      return getAreaFieldBuilder().addBuilder(
          index, com.grpc.area.Area.getDefaultInstance());
    }
    /**
     * <code>repeated .com.grpc.area.Area area = 5;</code>
     */
    public java.util.List<com.grpc.area.Area.Builder> 
         getAreaBuilderList() {
      return getAreaFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.area.Area, com.grpc.area.Area.Builder, com.grpc.area.AreaOrBuilder> 
        getAreaFieldBuilder() {
      if (areaBuilder_ == null) {
        areaBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.grpc.area.Area, com.grpc.area.Area.Builder, com.grpc.area.AreaOrBuilder>(
                area_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        area_ = null;
      }
      return areaBuilder_;
    }

    private java.lang.Object zipCode_ = "";
    /**
     * <code>string zip_code = 6;</code>
     */
    public java.lang.String getZipCode() {
      java.lang.Object ref = zipCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zipCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string zip_code = 6;</code>
     */
    public com.google.protobuf.ByteString
        getZipCodeBytes() {
      java.lang.Object ref = zipCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zipCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string zip_code = 6;</code>
     */
    public Builder setZipCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      zipCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string zip_code = 6;</code>
     */
    public Builder clearZipCode() {
      
      zipCode_ = getDefaultInstance().getZipCode();
      onChanged();
      return this;
    }
    /**
     * <code>string zip_code = 6;</code>
     */
    public Builder setZipCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      zipCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cityCode_ = "";
    /**
     * <code>string city_code = 7;</code>
     */
    public java.lang.String getCityCode() {
      java.lang.Object ref = cityCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cityCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string city_code = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCityCodeBytes() {
      java.lang.Object ref = cityCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cityCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string city_code = 7;</code>
     */
    public Builder setCityCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cityCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string city_code = 7;</code>
     */
    public Builder clearCityCode() {
      
      cityCode_ = getDefaultInstance().getCityCode();
      onChanged();
      return this;
    }
    /**
     * <code>string city_code = 7;</code>
     */
    public Builder setCityCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cityCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 8;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 8;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 8;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 8;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 8;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object shortName_ = "";
    /**
     * <code>string short_name = 9;</code>
     */
    public java.lang.String getShortName() {
      java.lang.Object ref = shortName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shortName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string short_name = 9;</code>
     */
    public com.google.protobuf.ByteString
        getShortNameBytes() {
      java.lang.Object ref = shortName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shortName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string short_name = 9;</code>
     */
    public Builder setShortName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      shortName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string short_name = 9;</code>
     */
    public Builder clearShortName() {
      
      shortName_ = getDefaultInstance().getShortName();
      onChanged();
      return this;
    }
    /**
     * <code>string short_name = 9;</code>
     */
    public Builder setShortNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      shortName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mergerName_ = "";
    /**
     * <code>string merger_name = 10;</code>
     */
    public java.lang.String getMergerName() {
      java.lang.Object ref = mergerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mergerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string merger_name = 10;</code>
     */
    public com.google.protobuf.ByteString
        getMergerNameBytes() {
      java.lang.Object ref = mergerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mergerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string merger_name = 10;</code>
     */
    public Builder setMergerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mergerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string merger_name = 10;</code>
     */
    public Builder clearMergerName() {
      
      mergerName_ = getDefaultInstance().getMergerName();
      onChanged();
      return this;
    }
    /**
     * <code>string merger_name = 10;</code>
     */
    public Builder setMergerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mergerName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pinyin_ = "";
    /**
     * <code>string pinyin = 11;</code>
     */
    public java.lang.String getPinyin() {
      java.lang.Object ref = pinyin_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pinyin_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pinyin = 11;</code>
     */
    public com.google.protobuf.ByteString
        getPinyinBytes() {
      java.lang.Object ref = pinyin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pinyin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pinyin = 11;</code>
     */
    public Builder setPinyin(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pinyin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pinyin = 11;</code>
     */
    public Builder clearPinyin() {
      
      pinyin_ = getDefaultInstance().getPinyin();
      onChanged();
      return this;
    }
    /**
     * <code>string pinyin = 11;</code>
     */
    public Builder setPinyinBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pinyin_ = value;
      onChanged();
      return this;
    }

    private float lng_ ;
    /**
     * <code>float lng = 12;</code>
     */
    public float getLng() {
      return lng_;
    }
    /**
     * <code>float lng = 12;</code>
     */
    public Builder setLng(float value) {
      
      lng_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float lng = 12;</code>
     */
    public Builder clearLng() {
      
      lng_ = 0F;
      onChanged();
      return this;
    }

    private float lat_ ;
    /**
     * <code>float lat = 13;</code>
     */
    public float getLat() {
      return lat_;
    }
    /**
     * <code>float lat = 13;</code>
     */
    public Builder setLat(float value) {
      
      lat_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float lat = 13;</code>
     */
    public Builder clearLat() {
      
      lat_ = 0F;
      onChanged();
      return this;
    }

    private java.util.List<com.grpc.area.AreaTree> tree_ =
      java.util.Collections.emptyList();
    private void ensureTreeIsMutable() {
      if (!((bitField0_ & 0x00002000) == 0x00002000)) {
        tree_ = new java.util.ArrayList<com.grpc.area.AreaTree>(tree_);
        bitField0_ |= 0x00002000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.area.AreaTree, com.grpc.area.AreaTree.Builder, com.grpc.area.AreaTreeOrBuilder> treeBuilder_;

    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public java.util.List<com.grpc.area.AreaTree> getTreeList() {
      if (treeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tree_);
      } else {
        return treeBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public int getTreeCount() {
      if (treeBuilder_ == null) {
        return tree_.size();
      } else {
        return treeBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public com.grpc.area.AreaTree getTree(int index) {
      if (treeBuilder_ == null) {
        return tree_.get(index);
      } else {
        return treeBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public Builder setTree(
        int index, com.grpc.area.AreaTree value) {
      if (treeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTreeIsMutable();
        tree_.set(index, value);
        onChanged();
      } else {
        treeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public Builder setTree(
        int index, com.grpc.area.AreaTree.Builder builderForValue) {
      if (treeBuilder_ == null) {
        ensureTreeIsMutable();
        tree_.set(index, builderForValue.build());
        onChanged();
      } else {
        treeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public Builder addTree(com.grpc.area.AreaTree value) {
      if (treeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTreeIsMutable();
        tree_.add(value);
        onChanged();
      } else {
        treeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public Builder addTree(
        int index, com.grpc.area.AreaTree value) {
      if (treeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTreeIsMutable();
        tree_.add(index, value);
        onChanged();
      } else {
        treeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public Builder addTree(
        com.grpc.area.AreaTree.Builder builderForValue) {
      if (treeBuilder_ == null) {
        ensureTreeIsMutable();
        tree_.add(builderForValue.build());
        onChanged();
      } else {
        treeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public Builder addTree(
        int index, com.grpc.area.AreaTree.Builder builderForValue) {
      if (treeBuilder_ == null) {
        ensureTreeIsMutable();
        tree_.add(index, builderForValue.build());
        onChanged();
      } else {
        treeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public Builder addAllTree(
        java.lang.Iterable<? extends com.grpc.area.AreaTree> values) {
      if (treeBuilder_ == null) {
        ensureTreeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tree_);
        onChanged();
      } else {
        treeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public Builder clearTree() {
      if (treeBuilder_ == null) {
        tree_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
        onChanged();
      } else {
        treeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public Builder removeTree(int index) {
      if (treeBuilder_ == null) {
        ensureTreeIsMutable();
        tree_.remove(index);
        onChanged();
      } else {
        treeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public com.grpc.area.AreaTree.Builder getTreeBuilder(
        int index) {
      return getTreeFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public com.grpc.area.AreaTreeOrBuilder getTreeOrBuilder(
        int index) {
      if (treeBuilder_ == null) {
        return tree_.get(index);  } else {
        return treeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public java.util.List<? extends com.grpc.area.AreaTreeOrBuilder> 
         getTreeOrBuilderList() {
      if (treeBuilder_ != null) {
        return treeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tree_);
      }
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public com.grpc.area.AreaTree.Builder addTreeBuilder() {
      return getTreeFieldBuilder().addBuilder(
          com.grpc.area.AreaTree.getDefaultInstance());
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public com.grpc.area.AreaTree.Builder addTreeBuilder(
        int index) {
      return getTreeFieldBuilder().addBuilder(
          index, com.grpc.area.AreaTree.getDefaultInstance());
    }
    /**
     * <code>repeated .com.grpc.area.AreaTree tree = 20;</code>
     */
    public java.util.List<com.grpc.area.AreaTree.Builder> 
         getTreeBuilderList() {
      return getTreeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.area.AreaTree, com.grpc.area.AreaTree.Builder, com.grpc.area.AreaTreeOrBuilder> 
        getTreeFieldBuilder() {
      if (treeBuilder_ == null) {
        treeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.grpc.area.AreaTree, com.grpc.area.AreaTree.Builder, com.grpc.area.AreaTreeOrBuilder>(
                tree_,
                ((bitField0_ & 0x00002000) == 0x00002000),
                getParentForChildren(),
                isClean());
        tree_ = null;
      }
      return treeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.grpc.area.AreaResponse)
  }

  // @@protoc_insertion_point(class_scope:com.grpc.area.AreaResponse)
  private static final com.grpc.area.AreaResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.area.AreaResponse();
  }

  public static com.grpc.area.AreaResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AreaResponse>
      PARSER = new com.google.protobuf.AbstractParser<AreaResponse>() {
    @java.lang.Override
    public AreaResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AreaResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AreaResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AreaResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpc.area.AreaResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

