// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: area.proto

package com.grpc.area;

public final class AreaOuterClass {
  private AreaOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_area_Area_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_area_Area_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_area_AreaTree_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_area_AreaTree_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_area_AreaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_area_AreaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_area_AreaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_area_AreaResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\narea.proto\022\rcom.grpc.area\"\270\002\n\004Area\022\n\n\002" +
      "id\030\001 \001(\005\022\022\n\nlevel_code\030\002 \001(\005\022\023\n\013parent_c" +
      "ode\030\003 \001(\t\022\021\n\tarea_code\030\004 \001(\t\022\020\n\010zip_code" +
      "\030\005 \001(\t\022\021\n\tcity_code\030\006 \001(\t\022\014\n\004name\030\007 \001(\t\022" +
      "\022\n\nshort_name\030\010 \001(\t\022\023\n\013merger_name\030\t \001(\t" +
      "\022\016\n\006pinyin\030\n \001(\t\022\013\n\003lng\030\014 \001(\002\022\013\n\003lat\030\r \001" +
      "(\002\022\016\n\006remark\030\016 \001(\t\022\023\n\013create_time\030\017 \001(\005\022" +
      "\023\n\013create_user\030\020 \001(\005\022\023\n\013update_time\030\021 \001(" +
      "\005\022\023\n\013update_user\030\022 \001(\005\"Z\n\010AreaTree\022\n\n\002id" +
      "\030\001 \001(\t\022\014\n\004code\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022&\n\005ch" +
      "ild\030\005 \003(\0132\027.com.grpc.area.AreaTree\"\342\002\n\013A" +
      "reaRequest\022\n\n\002id\030\001 \001(\005\022\022\n\nlevel_code\030\002 \001" +
      "(\005\022\023\n\013parent_code\030\003 \001(\t\022\021\n\tarea_code\030\004 \001" +
      "(\t\022!\n\004area\030\005 \003(\0132\023.com.grpc.area.Area\022\020\n" +
      "\010zip_code\030\006 \001(\t\022\021\n\tcity_code\030\007 \001(\t\022\014\n\004na" +
      "me\030\010 \001(\t\022\022\n\nshort_name\030\t \001(\t\022\023\n\013merger_n" +
      "ame\030\n \001(\t\022\016\n\006pinyin\030\013 \001(\t\022\013\n\003lng\030\014 \001(\002\022\013" +
      "\n\003lat\030\r \001(\002\022\016\n\006remark\030\016 \001(\t\022\023\n\013create_ti" +
      "me\030\017 \001(\005\022\023\n\013create_user\030\020 \001(\005\022\023\n\013update_" +
      "time\030\021 \001(\005\022\023\n\013update_user\030\022 \001(\005\"\246\002\n\014Area" +
      "Response\022\n\n\002id\030\001 \001(\005\022\022\n\nlevel_code\030\002 \001(\005" +
      "\022\023\n\013parent_code\030\003 \001(\t\022\021\n\tarea_code\030\004 \001(\t" +
      "\022!\n\004area\030\005 \003(\0132\023.com.grpc.area.Area\022\020\n\010z" +
      "ip_code\030\006 \001(\t\022\021\n\tcity_code\030\007 \001(\t\022\014\n\004name" +
      "\030\010 \001(\t\022\022\n\nshort_name\030\t \001(\t\022\023\n\013merger_nam" +
      "e\030\n \001(\t\022\016\n\006pinyin\030\013 \001(\t\022\013\n\003lng\030\014 \001(\002\022\013\n\003" +
      "lat\030\r \001(\002\022%\n\004tree\030\024 \003(\0132\027.com.grpc.area." +
      "AreaTree2\345\002\n\013AreaService\022C\n\010listArea\022\032.c" +
      "om.grpc.area.AreaRequest\032\033.com.grpc.area" +
      ".AreaResponse\022B\n\007addArea\022\032.com.grpc.area" +
      ".AreaRequest\032\033.com.grpc.area.AreaRespons" +
      "e\022E\n\nmodifyArea\022\032.com.grpc.area.AreaRequ" +
      "est\032\033.com.grpc.area.AreaResponse\022B\n\013getA" +
      "reaTree\022\032.com.grpc.area.AreaRequest\032\027.co" +
      "m.grpc.area.AreaTree\022B\n\007getArea\022\032.com.gr" +
      "pc.area.AreaRequest\032\033.com.grpc.area.Area" +
      "ResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_grpc_area_Area_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpc_area_Area_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_area_Area_descriptor,
        new java.lang.String[] { "Id", "LevelCode", "ParentCode", "AreaCode", "ZipCode", "CityCode", "Name", "ShortName", "MergerName", "Pinyin", "Lng", "Lat", "Remark", "CreateTime", "CreateUser", "UpdateTime", "UpdateUser", });
    internal_static_com_grpc_area_AreaTree_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpc_area_AreaTree_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_area_AreaTree_descriptor,
        new java.lang.String[] { "Id", "Code", "Name", "Child", });
    internal_static_com_grpc_area_AreaRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_grpc_area_AreaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_area_AreaRequest_descriptor,
        new java.lang.String[] { "Id", "LevelCode", "ParentCode", "AreaCode", "Area", "ZipCode", "CityCode", "Name", "ShortName", "MergerName", "Pinyin", "Lng", "Lat", "Remark", "CreateTime", "CreateUser", "UpdateTime", "UpdateUser", });
    internal_static_com_grpc_area_AreaResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_grpc_area_AreaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_area_AreaResponse_descriptor,
        new java.lang.String[] { "Id", "LevelCode", "ParentCode", "AreaCode", "Area", "ZipCode", "CityCode", "Name", "ShortName", "MergerName", "Pinyin", "Lng", "Lat", "Tree", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
