// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_area.proto

package com.grpc.user_area;

/**
 * Protobuf type {@code com.grpc.user_area.UserAreaRequest}
 */
public  final class UserAreaRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.grpc.user_area.UserAreaRequest)
    UserAreaRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserAreaRequest.newBuilder() to construct.
  private UserAreaRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserAreaRequest() {
    id_ = 0;
    userId_ = 0;
    userArea_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserAreaRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 16: {

            userId_ = input.readInt32();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              userArea_ = new java.util.ArrayList<com.grpc.user_area.UserArea>();
              mutable_bitField0_ |= 0x00000004;
            }
            userArea_.add(
                input.readMessage(com.grpc.user_area.UserArea.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        userArea_ = java.util.Collections.unmodifiableList(userArea_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.user_area.UserAreaOuterClass.internal_static_com_grpc_user_area_UserAreaRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.user_area.UserAreaOuterClass.internal_static_com_grpc_user_area_UserAreaRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.user_area.UserAreaRequest.class, com.grpc.user_area.UserAreaRequest.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int USERID_FIELD_NUMBER = 2;
  private int userId_;
  /**
   * <code>int32 userId = 2;</code>
   */
  public int getUserId() {
    return userId_;
  }

  public static final int USERAREA_FIELD_NUMBER = 5;
  private java.util.List<com.grpc.user_area.UserArea> userArea_;
  /**
   * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
   */
  public java.util.List<com.grpc.user_area.UserArea> getUserAreaList() {
    return userArea_;
  }
  /**
   * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
   */
  public java.util.List<? extends com.grpc.user_area.UserAreaOrBuilder> 
      getUserAreaOrBuilderList() {
    return userArea_;
  }
  /**
   * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
   */
  public int getUserAreaCount() {
    return userArea_.size();
  }
  /**
   * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
   */
  public com.grpc.user_area.UserArea getUserArea(int index) {
    return userArea_.get(index);
  }
  /**
   * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
   */
  public com.grpc.user_area.UserAreaOrBuilder getUserAreaOrBuilder(
      int index) {
    return userArea_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (userId_ != 0) {
      output.writeInt32(2, userId_);
    }
    for (int i = 0; i < userArea_.size(); i++) {
      output.writeMessage(5, userArea_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, userId_);
    }
    for (int i = 0; i < userArea_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, userArea_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.user_area.UserAreaRequest)) {
      return super.equals(obj);
    }
    com.grpc.user_area.UserAreaRequest other = (com.grpc.user_area.UserAreaRequest) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && (getUserId()
        == other.getUserId());
    result = result && getUserAreaList()
        .equals(other.getUserAreaList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId();
    if (getUserAreaCount() > 0) {
      hash = (37 * hash) + USERAREA_FIELD_NUMBER;
      hash = (53 * hash) + getUserAreaList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.user_area.UserAreaRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.user_area.UserAreaRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.user_area.UserAreaRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.user_area.UserAreaRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.user_area.UserAreaRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.user_area.UserAreaRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.user_area.UserAreaRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.user_area.UserAreaRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.user_area.UserAreaRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.user_area.UserAreaRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.user_area.UserAreaRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.user_area.UserAreaRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.user_area.UserAreaRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.grpc.user_area.UserAreaRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.grpc.user_area.UserAreaRequest)
      com.grpc.user_area.UserAreaRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.user_area.UserAreaOuterClass.internal_static_com_grpc_user_area_UserAreaRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.user_area.UserAreaOuterClass.internal_static_com_grpc_user_area_UserAreaRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.user_area.UserAreaRequest.class, com.grpc.user_area.UserAreaRequest.Builder.class);
    }

    // Construct using com.grpc.user_area.UserAreaRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUserAreaFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      userId_ = 0;

      if (userAreaBuilder_ == null) {
        userArea_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        userAreaBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.user_area.UserAreaOuterClass.internal_static_com_grpc_user_area_UserAreaRequest_descriptor;
    }

    @java.lang.Override
    public com.grpc.user_area.UserAreaRequest getDefaultInstanceForType() {
      return com.grpc.user_area.UserAreaRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpc.user_area.UserAreaRequest build() {
      com.grpc.user_area.UserAreaRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpc.user_area.UserAreaRequest buildPartial() {
      com.grpc.user_area.UserAreaRequest result = new com.grpc.user_area.UserAreaRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.userId_ = userId_;
      if (userAreaBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          userArea_ = java.util.Collections.unmodifiableList(userArea_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.userArea_ = userArea_;
      } else {
        result.userArea_ = userAreaBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.user_area.UserAreaRequest) {
        return mergeFrom((com.grpc.user_area.UserAreaRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.user_area.UserAreaRequest other) {
      if (other == com.grpc.user_area.UserAreaRequest.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getUserId() != 0) {
        setUserId(other.getUserId());
      }
      if (userAreaBuilder_ == null) {
        if (!other.userArea_.isEmpty()) {
          if (userArea_.isEmpty()) {
            userArea_ = other.userArea_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureUserAreaIsMutable();
            userArea_.addAll(other.userArea_);
          }
          onChanged();
        }
      } else {
        if (!other.userArea_.isEmpty()) {
          if (userAreaBuilder_.isEmpty()) {
            userAreaBuilder_.dispose();
            userAreaBuilder_ = null;
            userArea_ = other.userArea_;
            bitField0_ = (bitField0_ & ~0x00000004);
            userAreaBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUserAreaFieldBuilder() : null;
          } else {
            userAreaBuilder_.addAllMessages(other.userArea_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.user_area.UserAreaRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.user_area.UserAreaRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private int userId_ ;
    /**
     * <code>int32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }
    /**
     * <code>int32 userId = 2;</code>
     */
    public Builder setUserId(int value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 userId = 2;</code>
     */
    public Builder clearUserId() {
      
      userId_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.grpc.user_area.UserArea> userArea_ =
      java.util.Collections.emptyList();
    private void ensureUserAreaIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        userArea_ = new java.util.ArrayList<com.grpc.user_area.UserArea>(userArea_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.user_area.UserArea, com.grpc.user_area.UserArea.Builder, com.grpc.user_area.UserAreaOrBuilder> userAreaBuilder_;

    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public java.util.List<com.grpc.user_area.UserArea> getUserAreaList() {
      if (userAreaBuilder_ == null) {
        return java.util.Collections.unmodifiableList(userArea_);
      } else {
        return userAreaBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public int getUserAreaCount() {
      if (userAreaBuilder_ == null) {
        return userArea_.size();
      } else {
        return userAreaBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public com.grpc.user_area.UserArea getUserArea(int index) {
      if (userAreaBuilder_ == null) {
        return userArea_.get(index);
      } else {
        return userAreaBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public Builder setUserArea(
        int index, com.grpc.user_area.UserArea value) {
      if (userAreaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserAreaIsMutable();
        userArea_.set(index, value);
        onChanged();
      } else {
        userAreaBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public Builder setUserArea(
        int index, com.grpc.user_area.UserArea.Builder builderForValue) {
      if (userAreaBuilder_ == null) {
        ensureUserAreaIsMutable();
        userArea_.set(index, builderForValue.build());
        onChanged();
      } else {
        userAreaBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public Builder addUserArea(com.grpc.user_area.UserArea value) {
      if (userAreaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserAreaIsMutable();
        userArea_.add(value);
        onChanged();
      } else {
        userAreaBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public Builder addUserArea(
        int index, com.grpc.user_area.UserArea value) {
      if (userAreaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserAreaIsMutable();
        userArea_.add(index, value);
        onChanged();
      } else {
        userAreaBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public Builder addUserArea(
        com.grpc.user_area.UserArea.Builder builderForValue) {
      if (userAreaBuilder_ == null) {
        ensureUserAreaIsMutable();
        userArea_.add(builderForValue.build());
        onChanged();
      } else {
        userAreaBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public Builder addUserArea(
        int index, com.grpc.user_area.UserArea.Builder builderForValue) {
      if (userAreaBuilder_ == null) {
        ensureUserAreaIsMutable();
        userArea_.add(index, builderForValue.build());
        onChanged();
      } else {
        userAreaBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public Builder addAllUserArea(
        java.lang.Iterable<? extends com.grpc.user_area.UserArea> values) {
      if (userAreaBuilder_ == null) {
        ensureUserAreaIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, userArea_);
        onChanged();
      } else {
        userAreaBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public Builder clearUserArea() {
      if (userAreaBuilder_ == null) {
        userArea_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        userAreaBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public Builder removeUserArea(int index) {
      if (userAreaBuilder_ == null) {
        ensureUserAreaIsMutable();
        userArea_.remove(index);
        onChanged();
      } else {
        userAreaBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public com.grpc.user_area.UserArea.Builder getUserAreaBuilder(
        int index) {
      return getUserAreaFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public com.grpc.user_area.UserAreaOrBuilder getUserAreaOrBuilder(
        int index) {
      if (userAreaBuilder_ == null) {
        return userArea_.get(index);  } else {
        return userAreaBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public java.util.List<? extends com.grpc.user_area.UserAreaOrBuilder> 
         getUserAreaOrBuilderList() {
      if (userAreaBuilder_ != null) {
        return userAreaBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(userArea_);
      }
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public com.grpc.user_area.UserArea.Builder addUserAreaBuilder() {
      return getUserAreaFieldBuilder().addBuilder(
          com.grpc.user_area.UserArea.getDefaultInstance());
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public com.grpc.user_area.UserArea.Builder addUserAreaBuilder(
        int index) {
      return getUserAreaFieldBuilder().addBuilder(
          index, com.grpc.user_area.UserArea.getDefaultInstance());
    }
    /**
     * <code>repeated .com.grpc.user_area.UserArea userArea = 5;</code>
     */
    public java.util.List<com.grpc.user_area.UserArea.Builder> 
         getUserAreaBuilderList() {
      return getUserAreaFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.grpc.user_area.UserArea, com.grpc.user_area.UserArea.Builder, com.grpc.user_area.UserAreaOrBuilder> 
        getUserAreaFieldBuilder() {
      if (userAreaBuilder_ == null) {
        userAreaBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.grpc.user_area.UserArea, com.grpc.user_area.UserArea.Builder, com.grpc.user_area.UserAreaOrBuilder>(
                userArea_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        userArea_ = null;
      }
      return userAreaBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.grpc.user_area.UserAreaRequest)
  }

  // @@protoc_insertion_point(class_scope:com.grpc.user_area.UserAreaRequest)
  private static final com.grpc.user_area.UserAreaRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.user_area.UserAreaRequest();
  }

  public static com.grpc.user_area.UserAreaRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserAreaRequest>
      PARSER = new com.google.protobuf.AbstractParser<UserAreaRequest>() {
    @java.lang.Override
    public UserAreaRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserAreaRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserAreaRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserAreaRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpc.user_area.UserAreaRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

